---
- hosts: localhost
  gather_facts: no
  become: yes
  become_user: root
  tasks:
    - name: " ******* STAGE 0 *******"
      debug: msg=" >>> Check Ansible Set Up <<<"

    - name: "Test file"
      copy:
        src: test.txt
        dest: /root/zeus/test.txt
